version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:alpine
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Check Gcloud version #1
          command: gcloud version
      - run: 
          name: Install Docker client #2
          command: |
            curl -fSL "https://get.docker.com/builds/Linux/x86_64/docker-17.03.0-ce.tgz" -o docker.tgz
            tar -xzvf docker.tgz
            mv docker/* /usr/local/bin/
            rmdir docker
            rm docker.tgz
            docker -v
      - run:
          name: Build Docker image #4
          command: |
            docker build . -t giangnguyen/express-server:dev
      - run:
          name: Push Docker Image to GCR registry #5
          command: |
             docker push giangnguyen/express-server:dev